application: karra-asynk
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /doc
  static_dir: doc

- url: /downloads
  static_dir: downloads

- url: /.*
  script: asynk.py

builtins:
- datastore_admin: on
